# Generated by Django 4.1.7 on 2023-02-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='job_des',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='years',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='work',
            name='years',
            field=models.CharField(max_length=25),
        ),
    ]
