# Generated by Django 4.1.7 on 2023-03-27 22:29

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_work_job_des_alter_education_years_alter_work_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.filepath),
        ),
    ]
